[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = ["*"]

[[redirects]]
  from = "https://url-shortner-brasil-back-end.netlify.app/"
  to = "index.html"
  status = 200
  force = true